<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

/**
 * 24HourRunHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HourRunHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
