<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\Organization;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get organization from database by uuid
     * @param $uuid
     * @return Organization;
     */
    public function getByUuid($uuid)
    {
        return $this->getEntityManager()
            ->getRepository('\Sentegrity\BusinessBundle\Entity\Documents\Organization')
            ->findOneBy(array(
                'uuid' => $uuid
            ));
    }
}
