<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;
use Sentegrity\BusinessBundle\Entity\Documents\Policy;

/**
 * PolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get policy from database by uuid
     * @param $uuid
     * @return Policy;
     */
    public function getByUuid($uuid)
    {
        return $this->getEntityManager()
            ->getRepository('\Sentegrity\BusinessBundle\Entity\Documents\Policy')
            ->findOneBy(array(
                'uuid' => $uuid
            ));
    }
}
