<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\AdminUser;
use Symfony\Bridge\Doctrine;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Gets user from db by it's credentials
     *
     * @param $username
     * @param $password
     * @return AdminUser
     */
    public function getUserByUsernameAndPassword($username, $password)
    {
        return $this->findOneBy(array(
            'username' => $username,
            'password' => $password
        ));
    }
}
