<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\AdminSession;
use Symfony\Bridge\Doctrine;

/**
 * AdminSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminSessionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $accessToken
     * @return AdminSession
     */
    public function getSessionByAccessToken($accessToken)
    {
        return $this->findOneBy(array(
            'accessToken' => $accessToken
        ));
    }
}
