<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\Groups;
use Sentegrity\BusinessBundle\Entity\Documents\Organization;
use Symfony\Component\Validator\Tests\Fixtures\Entity;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get group from database by group and organization
     * @param $groupId
     * @param Organization $organization
     * @return Groups;
     */
    public function getByGroupAndOrganization($groupId, Organization $organization)
    {
        return $this->findOneBy(array(
                'groupId' => $groupId,
                'organization' => $organization
            ));
    }

    /**
     * Get default group for multiple organizations
     * @param array $organizations
     * @return array;
     */
    public function getDefaultGroupsByMultipleOrganizations(array $organizations)
    {
        return $this->findBy(array(
            'groupId' => 0,
            'organization' => $organizations
        ));
    }

    /**
     * Deletes all groups from an organization
     * @param Organization $organization
     * @return bool
     */
    public function deleteByOrganization(Organization $organization)
    {
        return $this->createQueryBuilder('groups')
            ->delete()
            ->where('groups.organization = :organization')
            ->setParameter('organization', $organization)
            ->getQuery()
            ->execute();
    }
}
