<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\Organization;
use Symfony\Bridge\Doctrine;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get organization from database by uuid
     * @param $uuid
     * @return Organization;
     */
    public function getByUuid($uuid)
    {
        return $this->findOneBy(array(
                'uuid' => $uuid
            ));
    }

    /**
     * Get organization database id by uuid
     * @param $uuid
     * @return int $id;
     */
    public function getIdByUuid($uuid)
    {
        $qb = $this->createQueryBuilder('organization')
            ->select('organization.id')
            ->where('organization.uuid = :uuid')
            ->setParameter('uuid', $uuid)
            ->getQuery()
            ->execute();

        if (!$qb) {
            return 0;
        }
        return (int)$qb[0]['id'];
    }

    /**
     * Gets all organizations in the system
     *
     * @param $offset
     * @param $limit
     * @return array
     */
    public function getAll($offset, $limit)
    {
        return $this->findBy(
            [], null, $limit, $offset
        );
    }
}
