<?php

namespace Sentegrity\BusinessBundle\Entity\Repository;

use Sentegrity\BusinessBundle\Entity\Documents\Policy;

/**
 * PolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get policy from database by uuid
     * @param $uuid
     * @return Policy;
     */
    public function getByUuid($uuid)
    {
        return $this->findOneBy(array(
                'uuid' => $uuid
            ));
    }

    /**
     * Get all policies of an organization
     * @param $id -> organization owner id
     * @param $offset
     * @param $limit
     * @return array
     */
    public function getByOrganization($id, $offset, $limit)
    {
        // along an organization id system should use 0 as default
        // policies should also be returned
        $criteria = [0, $id];
        return $this->findBy(array(
            'organizationOwnerId' => $criteria
        ), null, $limit, $offset);
    }

    /**
     * Get all policies (if sentegrity is asking)
     * @param $offset
     * @param $limit
     * @return array
     */
    public function getAll($offset, $limit)
    {
        return $this->findBy(
            [], null, $limit, $offset
        );
    }
}
