parameters:
    default_policy: default
    required_request_data:
        - email
        - deviceSalt
        - runHistoryObjects
        - policyID
        - policyRevision
        - platform
        - currentAppVersion

    ## support
    database_dsn: mysql:dbname=%database_name%;host=%database_host%;port=%database_port%;charset=utf8mb4
    pdo.attr_errmode: 3
    pdo.erromode_exception: 2
    pdo.options:
        %pdo.attr_errmode%: %pdo.erromode_exception%

    ## validators
    validate_organization_create:
        - name
        - domain_name
        - contact_name
        - contact_email
        - contact_phone
        - policy_ios
        - policy_android

    validate_policy_create:
        - name
        - platform
        - is_default
        - app_version
        - data

    validate_load_get:
        - offset
        - limit

    validate_sign_in:
        - username
        - password

    validate_dashboard_get:
        - time_frame