parameters:
    default_policy: default
    required_request_data:
        - email
        - deviceSalt
        - runHistoryObjects
        - policyID
        - policyRevision
        - platform
        - currentAppVersion