parameters:
    policy_location: %resources_path%policy/
    data_location: %resources_path%data/
    default_policy: default
    required_request_data:
        - email
        - deviceSalt
        - runHistoryObjects
        - policyID
        - policyRevision
        - platform
        - currentAppVersion