services:
    sentegrity_business.policy:
        class: Sentegrity\BusinessBundle\Services\Admin\Policy
        arguments: ['@service_container']

    sentegrity_business.organization:
        class: Sentegrity\BusinessBundle\Services\Admin\Organization
        arguments: ['@service_container']

    sentegrity_business.group:
        class: Sentegrity\BusinessBundle\Services\Admin\Group
        arguments: ['@service_container']

    sentegrity_business.sign_in:
        class: Sentegrity\BusinessBundle\Services\Admin\SignIn
        arguments: ['@service_container']

    sentegrity_business.error_log:
            class: Sentegrity\BusinessBundle\Services\Support\ErrorLog
            arguments: ['@service_container']


    ## api related
    sentegrity_business.api.user:
        class: Sentegrity\BusinessBundle\Services\Api\User
        arguments: ['@service_container']

    sentegrity_business.api.policy:
        class: Sentegrity\BusinessBundle\Services\Api\Policy
        arguments: ['@service_container']

    sentegrity_business.api.organization:
        class: Sentegrity\BusinessBundle\Services\Api\Organization
        arguments: ['@service_container']

    sentegrity_business.api.check_in:
        class: Sentegrity\BusinessBundle\Services\Api\CheckIn
        arguments: ['@service_container']

    sentegrity_business.api.run_history:
        class: Sentegrity\BusinessBundle\Services\Api\RunHistory
        arguments: ['@service_container']


    ## Support stuff
    pdo_master_connection:
        class: PDO
        arguments: ["%database_dsn%", "%database_user%", "%database_password%", "%pdo.options%"]

    pdo_slave_connection:
        class: Sentegrity\BusinessBundle\Services\Support\Database\PDOSlave
        arguments: ["%slave_database_hosts%", "%database_name%", "%database_user%", "%database_password%", "%pdo.options%"]

    sentegrity_business.exception_listener:
        class: Sentegrity\BusinessBundle\EventListener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    validation_annotation_driver:
        class: Sentegrity\BusinessBundle\Annotations\Driver\ValidatorDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]     # Point event
        arguments: ['@annotation_reader', '@request_stack']

    permission_anotation_driver:
        class: Sentegrity\BusinessBundle\Annotations\Driver\PermissionDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]     # Point event
        arguments: ['@annotation_reader', '@request_stack', '@doctrine.orm.entity_manager']

    my_sql_query:
        class: Sentegrity\BusinessBundle\Services\Support\Database\MySQLQuery
        arguments: ['@pdo_master_connection', '@pdo_slave_connection']

    ## Batch
    sentegrity_business.batch.daily:
        class: Sentegrity\BusinessBundle\BatchJobs\Daily
        arguments: ['@service_container']