services:
    sentegrity_business.run_history:
        class: Sentegrity\BusinessBundle\Services\RunHistory
        arguments: ['@service_container']

    sentegrity_business.policy:
        class: Sentegrity\BusinessBundle\Services\Policy
        arguments: ['@service_container']

    sentegrity_business.exception_listener:
        class: Sentegrity\BusinessBundle\EventListener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
